// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIDtVj76e83p-PQ0r7yyBupAfHCjnt7IY',
    appId: '1:407821099676:web:d01e1cd5e561bbff22c359',
    messagingSenderId: '407821099676',
    projectId: 'todocleanarch',
    authDomain: 'todocleanarch.firebaseapp.com',
    storageBucket: 'todocleanarch.appspot.com',
    measurementId: 'G-KBXDB8PTRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDObgNdzNXJHlEBIPzPwrFeer-Z50-ibQM',
    appId: '1:407821099676:android:c896219b65e8adec22c359',
    messagingSenderId: '407821099676',
    projectId: 'todocleanarch',
    storageBucket: 'todocleanarch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKF2ou5Cr5K_nzZ7cI0QW8nBPov4RlmDg',
    appId: '1:407821099676:ios:158d3d0aab76d6df22c359',
    messagingSenderId: '407821099676',
    projectId: 'todocleanarch',
    storageBucket: 'todocleanarch.appspot.com',
    iosBundleId: 'com.example.todoWithCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKF2ou5Cr5K_nzZ7cI0QW8nBPov4RlmDg',
    appId: '1:407821099676:ios:46a423e8fd69c13022c359',
    messagingSenderId: '407821099676',
    projectId: 'todocleanarch',
    storageBucket: 'todocleanarch.appspot.com',
    iosBundleId: 'com.example.todoWithCleanArchitecture.RunnerTests',
  );
}
